### ISSUE TITLE
i2pwinupdate.su3 doesn't run

### ISSUE THREAD

**Issue by GirkovArpa** [eyedeekay/i2p.firefox#3]
Windows can't run this file.  Thought this project was for simplifying installation of i2p without having to install Java and whatnot, but apparently this is even more complicated.  Never heard of an su3 file, but in the release notes it said it was an "EXE", so changed the extension to .exe and tried to run but ... nope.

**Comment by eyedeekay** [comment]
su3 is a signed zip file containing an exe. I honestly don't know how you even got it without an existing bundle installed. The I2P downloads it as an in-network torrent, checks the signature on it, extracts it and runs it. su3's don't get run manually by the user, it is only ever run by the router itself during the automatic update process. That's why you can't run it.

You can get the installer from here: https://files.i2p-projekt.de/1.9.0/I2P-Profile-Installer-1.9.0-signed.exe

**Comment by GirkovArpa** [comment]
I had got it from here lol:

- https://github.com/eyedeekay/i2p.firefox/releases/tag/2021-su3
